inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'test/**/*'
    - 'vendor/**/*'

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

HashSyntax:
  EnforcedStyle: ruby19

# 「change_table：users、bulk：true」を使用して、マイグレーションの高速化ができる
Rails/BulkChangeTable:
  Enabled: false

# if文の記述法修正
Style/ConditionalAssignment:
  Enabled: false

# deviseで生成されたコントローラーの修正
Style/ClassAndModuleChildren:
  Enabled: false