version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATAVASE: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/app_name
      - public-data:/app_name/public
      - tmp-data:/app_name/tmp
      - log-data:/app_name/log
    depends_on:
      - db
      - chrome
    tty: true
    stdin_open: true
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/app_name/public
      - tmp-data:/app_name/tmp
    ports:
      - 80:80
    depends_on:
      - app
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data:
